version: '3' 


services:
  express: 
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  angular:
    hostname: localhost
    
    build:     
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express